### ISSUE TITLE
Chatbot

### ISSUE THREAD

**Issue by mezgoodle** [mezgoodle/FundFriend#8]
[Documentation](https://learn.microsoft.com/ru-ru/azure/bot-service/index-bf-sdk?view=azure-bot-service-4.0), [video](https://www.youtube.com/watch?v=XnLVcNplFEQ&ab_channel=LearnMicrosoftAI)

- [x] Simple response
- [x] Tests with the specific library - in the #14 
- [x] Linter
- [x] CI/CD
- [x] Luis - in the #15 
- [x] QNA - in the #16 

Other books about Dialogflow:
- [Book](https://drive.google.com/file/d/1JXUxGkJh269qYPmMvh3zwjHaVyrjdWqJ/view?usp=drive_link)
- [Another book](https://drive.google.com/file/d/1mcJNtwESxoVQJaRAdqLkuV1UcnFBaFqb/view?usp=drive_link)
